# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WHDetection
                                 A QGIS plugin
 This plugin allows the detection of Water Hyacinth plants through vegetation indices and remote sensing images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-21
        copyright            : (C) 2021 by Luís Pádua and Lia Duarte
        email                : liaduarte@fc.up.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WHDetection class from file WHDetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .WH_Detection import WHDetection
    return WHDetection(iface)
